---
title: "Final Project Regression with ARIMA Errors"
output: html_notebook
author: "Sai Krishna"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 
```

```{r include = FALSE}
setwd("C:/Users/saikr/Desktop/Q4/Time Series/Final Project")
```

```{r}
library(forecast)
library(tseries)
library(ggplot2)
library(fpp)
library(tidyverse)
```


```{r}
weather_data <- read.csv("final_data_2000_2023.csv")
weather_data$avgTemp = (weather_data$tempmax + weather_data$tempmin)/2
df_ts <- ts(weather_data, start = c(2000, 1), frequency = 365.25)
plot(df_ts[,'temp'])
checkresiduals(df_ts[,'temp'])
```

```{r}
df_ts[,'avgTemp'] <- df_ts[,'avgTemp']+50
df_ts[,'tempmax'] <- df_ts[,'tempmax']+50
df_ts[,'tempmin'] <- df_ts[,'tempmin']+50
df_ts[,'temp'] <- df_ts[,'temp']+50
```

Check for variance in the data
```{r}
BoxCox.lambda(df_ts[,'temp'])
```
### There is indeed variance in the data and should use lambda 2 for stabilizing it

```{r}
df_reg <- weather_data %>% select(-feelslikemax,
                        -feelslikemin,
                        -feelslike,
                        -name,
                        -conditions,
                        -description,
                        -stations,
                        -sunset,
                        -sunrise,
                        -preciptype,
                        -icon,
                        -datetime,
                        -avgTemp,
                        -tempmax, 
                        -tempmin,
                        -precipprob,
                        -severerisk)
```

```{r}
df_reg$windgust <- ifelse(is.na(df_reg$windgust), 0, df_reg$windgust)
df_reg$temp <- df_reg$temp + 50
# df_reg$severerisk <- ifelse(is.na(df_reg$severerisk), 0, df_reg$severerisk)
```


## Check for the best model for forecasting temp

```{r}
df_temp_ts <- ts(df_reg, start = c(2000, 1), frequency = 365.25)
# Box Cox
df_reg_ts_bc <- df_temp_ts
df_reg_ts_bc[,"temp"] <- BoxCox(df_temp_ts[,"temp"], lambda = 2)

y_day21 <- as.numeric(as.POSIXlt("2021-05-31")$yday)
train_temp <- window(df_reg_ts_bc, start = c(2000, 1), end = c(2021, y_day21))
train_temp2 <- window(df_temp_ts, start = c(2000, 1), end = c(2021, y_day21))

yday_23 <- as.numeric(as.POSIXlt("2023-07-31")$yday)
temp_test <- window(df_reg_ts_bc, start = c(2021, y_day21 + 1), end = c(2023, yday_23))
temp_test2 <- window(df_temp_ts, start = c(2021, y_day21 + 1), end = c(2023, yday_23))
```


## Forward stepwise selection
```{r}
library(leaps)
```


```{r}
regfit <- regsubsets(temp ~., 
                     data = train_temp2, 
                     nvmax = 16,
                     method = "forward")
```

```{r}
summary(regfit)
```

```{r}
# check error using test data
test.mat <- model.matrix(temp ~., data = as.data.frame(temp_test2))

val.error <- rep(NA, 16)
for (i in 1:16) {
  coefi = coef(regfit, id = i)
  pred = test.mat[, names(coefi)]%*%coefi
  val.error[i] = mean((temp_test2[, "temp"] - pred)^2)
}
val.error

coef(regfit, which.min(val.error))
```
#### Best model at p =8
```{r}
# best model (p = 8)
bestfit <- tslm(temp ~ dew + humidity + precipcover + snow + windspeed +
                  sealevelpressure + cloudcover + visibility,
                data = train_temp2,
                lambda = 2)

summary(bestfit)
```

```{r}
checkresiduals(bestfit)
```

- Need to do regression with ARIMA errors.

```{r}
xreg <- cbind(dew = train_temp2[, "dew"],
              humidity = train_temp2[, "humidity"],
              precipcover = train_temp2[, "precipcover"],
              snow = train_temp2[, "snow"],
              windspeed = train_temp2[,"windspeed"],
              sealevelpressure = train_temp2[, "sealevelpressure"],
              cloudcover = train_temp2[, "cloudcover"],
              visibility = train_temp2[, "visibility"])

reg_w_arima <- auto.arima(train_temp2[, "temp"],
                          lambda = 2,
                          xreg = xreg, num.cores = 10)

summary(reg_w_arima)
checkresiduals(reg_w_arima)
```

```{r}
# Generate forecasts without specifying xreg argument
forecast_reg <- forecast(reg_w_arima, h = 3,
                         xreg = cbind(dew = temp_test2[, "dew"],
                                      humidity = temp_test2[, "humidity"],
                                      precipcover = temp_test2[, "precipcover"],
                                      snow = temp_test2[, "snow"],
                                      windspeed = temp_test2[, "windspeed"],
                                      sealevelpressure = temp_test2[, "sealevelpressure"],
                                      cloudcover = temp_test2[, "cloudcover"],
                                      visibility = temp_test2[, "visibility"]))

# Print the forecasted values
print(forecast_reg)
```

```{r}
# plot(forecast_reg)
# Create a plot with forecasted and actual values
plot <- autoplot(forecast_reg) + autolayer(temp_test2[,'temp'])
# Specify the x-axis limits for the last 4 years
last_year <- 2018
plot <- plot + scale_x_continuous(
  limits = c(last_year, 2024),
  breaks = seq(last_year, 2024, by = 1)
)
```


```{r}
plot
```

```{r}
accuracy(forecast_reg, (temp_test2[,'temp']-2))
```













```{r}
xreg <- cbind(dew = train_temp2[, "dew"],
              humidity = train_temp2[, "humidity"],
              precipcover = train_temp2[, "precipcover"],
              snow = train_temp2[, "snow"],
              windspeed = train_temp2[,"windspeed"],
              sealevelpressure = train_temp2[, "sealevelpressure"],
              cloudcover = train_temp2[, "cloudcover"],
              visibility = train_temp2[, "visibility"])

reg_w_sarima <- auto.arima(train_temp2[, "temp"],
                          lambda = 2, seasonal = TRUE, parallel = TRUE, max.D = 1,
                          xreg = xreg, num.cores = 12)

summary(reg_w_sarima)
checkresiduals(reg_w_sarima)
```

```{r}
# Generate forecasts without specifying xreg argument
forecast_reg.sarima <- forecast(reg_w_sarima, h = 3,
                         xreg = cbind(dew = temp_test2[, "dew"],
                                      humidity = temp_test2[, "humidity"],
                                      precipcover = temp_test2[, "precipcover"],
                                      snow = temp_test2[, "snow"],
                                      windspeed = temp_test2[, "windspeed"],
                                      sealevelpressure = temp_test2[, "sealevelpressure"],
                                      cloudcover = temp_test2[, "cloudcover"],
                                      visibility = temp_test2[, "visibility"]))

# Print the forecasted values
print(forecast_reg.sarima)
```



```{r}
accuracy(forecast_reg.sarima, temp_test2[,'temp'])
```


```{r}
# plot(forecast_reg)
# Create a plot with forecasted and actual values
plot <- autoplot(forecast_reg.sarima) + autolayer(temp_test2[,'temp'])
# Specify the x-axis limits for the last 4 years
last_year <- 2018
plot <- plot + scale_x_continuous(
  limits = c(last_year, 2024),
  breaks = seq(last_year, 2024, by = 1)
)
```


```{r}
plot
```






















